sudo: required
language: generic
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
    -in travis_rsa.enc -out travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_rsa
  - ssh-add travis_rsa
  - docker build -t ymtangab/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ymtangab/docker-react npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: make build && make release
  on:
    branch: master
